version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: app
    command: sh -c "yarn && yarn dev"
    working_dir: /app
    env_file:
      - .env.local
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - '3001:3000'

volumes:
  node_modules:
